### ISSUE TITLE
[NPU] 昇腾910B arm, run_check时报  ACL error, the error code is : 500001

### ISSUE THREAD

**Issue by cynicgit** [PaddlePaddle/PaddleCustomDevice#1214]
<img width="1305" alt="image" src="https://github.com/PaddlePaddle/PaddleCustomDevice/assets/11511900/481f1c1b-fce5-4595-96e7-e563d88e1f27">
paddlepaddle 和 PaddleCustomDevice都是develop分支版本

**Comment by ronny1996** [comment]
你好，请问用的什么镜像？

**Comment by cynicgit** [comment]
> 你好，请问用的什么镜像？

用的是华为提供的 unbutu 18.04 的镜像

**Comment by ronny1996** [comment]
你好，报错信息是CANN的JIT算子报错，可以尝试 export FLAGS_npu_jit_compile=false 关闭 jit

**Comment by ronny1996** [comment]
你好，可以尝试下 `export FLAGS_npu_jit_compile=false` 或者使用这个镜像 registry.baidubce.com/device/paddle-npu:cann80RC1-ubuntu20-x86_64-gcc84-py39

这个issue我先关了，如果还有问题可以再打开

**Comment by yangy996** [comment]
> export FLAGS_npu_jit_compile=false

还是不行，还是一样的错误：

**Comment by yangy996** [comment]
> > export FLAGS_npu_jit_compile=false
> 
> 还是不行，还是一样的错误：

<img width="1430" height="139" alt="Image" src="https://github.com/user-attachments/assets/ee198b95-5e46-4994-b94d-d3fc63ae95cb" />

<img width="1399" height="660" alt="Image" src="https://github.com/user-attachments/assets/101d14a1-40ed-46e6-b9d1-ae631bee24a3" />

**Comment by YongKuoD** [comment]
解决了吗，我这边也是同样的问题。

**Comment by yangy996** [comment]
> 解决了吗，我这边也是同样的问题。

我解决了，我的是内部缺少依赖包导致的，查看npu的日志才发现的，路径：/root/ascend/log/debug/plog/目录下

**Comment by 1556900941lizerui** [comment]
> > 解决了吗，我这边也是同样的问题。
> 
> 我解决了，我的是内部缺少依赖包导致的，查看npu的日志才发现的，路径：/root/ascend/log/debug/plog/目录下

感谢大佬终于解决了
